// enterprise/frontend/src/embedding-sdk/components/public/InteractiveDashboard/interactive-dashboard.web-component.tsx
import { createWebComponent } from "embedding-sdk/lib/web-components/create-web-component";

import {
  EditableDashboard,
  type EditableDashboardProps,
  type InteractiveDashboardProps,
} from "../InteractiveDashboard";

export type InteractiveDashboardWebComponentAttributes = {
  "dashboard-id": InteractiveDashboardProps["dashboardId"];
};

const InteractiveDashboardWebComponent = createWebComponent<
  Pick<EditableDashboardProps, "dashboardId">
>(({ dashboardId }) => <EditableDashboard dashboardId={dashboardId} />, {
  props: {
    dashboardId: "number",
  },
});

customElements.define(
  "interactive-dashboard",
  InteractiveDashboardWebComponent,
);

// enterprise/frontend/src/embedding-sdk/components/public/dashboard/InteractiveDashboard/interactive-dashboard.web-component.tsx
import {
  createWebComponent,
  registerWebComponent,
} from "embedding-sdk/lib/web-components";

import {
  InteractiveDashboard,
  type InteractiveDashboardProps,
} from "../InteractiveDashboard";

export type InteractiveDashboardWebComponentAttributes = {
  "dashboard-id": string;
  "with-downloads"?: string;
};

const InteractiveDashboardWebComponent = createWebComponent<
  Pick<InteractiveDashboardProps, "dashboardId" | "withDownloads">
>((props) => <InteractiveDashboard {...props} />, {
  propTypes: {
    dashboardId: "id",
    withDownloads: "boolean",
  },
});

registerWebComponent("interactive-dashboard", InteractiveDashboardWebComponent);
